version: 2
jobs:
  build:
    working_directory: ~/stock-tracker
    docker:
      # primary container to execute build in
      - image: circleci/node:12.12
    steps:
      # checkout source code to working directory
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  
  deploy:
    working_directory: ~/stock-tracker
    docker:
      - image: circleci/node:12.12
    steps:
      - run:
          name: do-deploy
          command: 'echo "deploying..."'
 
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy
          requires:
            - build


