version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  build:
    working_directory: ~/stock-tracker
    docker:
      # primary container to execute build in
      - image: circleci/node:12.12
    steps:
      # checkout source code to working directory
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

  deploy-to-azure:
    working_directory: ~/stock-tracker
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          name: az resource list
          command: List resources of tenant stored as 'AZURE_SP_TENANT' env var
 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-to-azure:
          requires:
            - build
          filters:
            branches:
              only: master
